var ps3Juegos = [
	["Assasins Creed Black Flag", "img/Covers_ps3/AC_4BlackFlag.jpeg", "8 Gb"],
	["Assasins Creed Rogue", "img/Covers_ps3/AC_Rogue.jpg", "6,3 Gb"],
	["Army Two The devils cartel","img/Covers_ps3/AOF_The_Devils_Cartel.jpg","6,9 Gb"],
	["Battlefield 4","img/Covers_ps3/Battlefiled_4.jpg","10 Gb"],
	["Blur","img/Covers_ps3/Blur.jpg","6 Gb"],
	["Call of duty Advanced Warfare","img/Covers_ps3/Cod_Advanced_Warfare.jpg","16 Gb"],
	["Call of duty Black ops","img/Covers_ps3/Cod_Black_Ops_2.jpg","12 Gb"],
	["Call of duty Ghost","img/Covers_ps3/Cod_Ghost.jpg","10,3 Gb"],
	["","img/Covers_ps3/Crysis.jpg",""],
	["","img/Covers_ps3/Crysis_2.jpg",""],
	["","img/Covers_ps3/DantesInferno.jpg",""],
	["","img/Covers_ps3/Dark_Souls.jpg",""],
	["","img/Covers_ps3/Dark_Souls_2.jpg",""],
	["","img/Covers_ps3/DeadPool.jpg",""],
	["","img/Covers_ps3/Dead_Space.jpg",""],
	["","img/Covers_ps3/Demons_Souls.jpg",""],
	["","img/Covers_ps3/DevilMayCry.jpg",""],
	["","img/Covers_ps3/DragonBallXenoberse.jpg",""],
	["","img/Covers_ps3/Ea_MMA.jpg",""],
	["","img/Covers_ps3/Fallout_3.jpeg",""],
	["","img/Covers_ps3/Farcry_2.jpg",""],
	["","img/Covers_ps3/Farcry_4.jpg",""],
	["","img/Covers_ps3/Fifa_19.jpg",""],
	["","img/Covers_ps3/Fifa_Street.jpg",""],
	["","img/Covers_ps3/GH_Aerosmith.jpg",""],
	["","img/Covers_ps3/GH_Legends_O_fRock.jpg",""],
	["","img/Covers_ps3/GOW_3.jpg",""],
	["","img/Covers_ps3/GOW_Ascension.jpg",""],
	["","img/Covers_ps3/GTAV.jpg",""],
	["","img/Covers_ps3/Just_Cause_2.jpg",""],
	["","img/Covers_ps3/Killzone.jpg",""],
	["","img/Covers_ps3/Killzone_2.jpg",""],
	["","img/Covers_ps3/Killzone_3.jpg",""],
	["","img/Covers_ps3/Little_Big_Planet.jpg",""],
	["","img/Covers_ps3/MedalOfHonorWarfighter.jpg",""],
	["","img/Covers_ps3/MGS_5_The_Phantom_Pain.jpg",""],
	["","img/Covers_ps3/Minecraft.jpg",""],
	["","img/Covers_ps3/Mirror's_Edge.jpg",""],
	["","img/Covers_ps3/Mortal_Kombat_9.jpg",""],
	["","img/Covers_ps3/Moto_Gp14.jpg",""],
	["","img/Covers_ps3/Mx_Vs_Atv_Supercross.jpg",""],
	["","img/Covers_ps3/NFS_Most_Wanted.jpg",""],
	["","img/Covers_ps3/NFS_Rivals.jpg",""],
	["","img/Covers_ps3/NFS_Run.jpg",""],
	["","img/Covers_ps3/Pes_2018.jpg",""],
	["","img/Covers_ps3/Portal_2.jpg",""],
	["","img/Covers_ps3/PS_AllStars_BattleRoyale.jpg",""],
	["","img/Covers_ps3/Rayman_Origins.jpg",""],
	["","img/Covers_ps3/Red_Dead_Redemption.jpg",""],
	["","img/Covers_ps3/Resident_Evil_4.jpg",""],
	["","img/Covers_ps3/Resident_Evil_5.jpg",""],
	["","img/Covers_ps3/Resident_Evil_6.jpg",""],
	["","img/Covers_ps3/Sniper_Elite_2.jpg",""],
	["","img/Covers_ps3/Sniper_Elite_3.jpg",""],
	["","img/Covers_ps3/Sniper_Ghost_Warrior_2.jpg",""],
	["","img/Covers_ps3/The_Evil_Within.jpg",""],
	["","img/Covers_ps3/TheLast_OfUs.jpg",""],
	["","img/Covers_ps3/Toy_Story3.jpg",""],
	["","img/Covers_ps3/W2k17.jpg",""],
	["","img/Covers_ps3/Watch_Dogs.jpeg",""],
	["","img/Covers_ps3/Wolfestein_TheNewOrder.jpg",""],

];